import { useEffect, useState } from "react";
import API from "../services/api";
import Modal from "../components/Modal";
import Loading from "../components/Loading";

const configs={suppliers:{title:"Suppliers",endpoint:"/suppliers",fields:[["name","Name"],["company","Company"],["email","Email","email"],["phone","Phone"],["address","Address"]]},customers:{title:"Customers",endpoint:"/customers",fields:[["name","Name"],["email","Email","email"],["phone","Phone"],["address","Address"]]}};
export default function Contacts({type}){const c=configs[type], [rows,setRows]=useState([]),[form,setForm]=useState({}),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const r=await API.get(c.endpoint);setRows(r.data)}catch(e){setError(e.response?.data?.message||"Unable to load data")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();try{if(editing)await API.put(`${c.endpoint}/${editing}`,form);else await API.post(c.endpoint,form);setShow(false);setEditing(null);setForm({});load()}catch(e){setError(e.response?.data?.message||"Could not save")}};
 const remove=async id=>{if(!confirm(`Delete this ${type.slice(0,-1)}?`))return;try{await API.delete(`${c.endpoint}/${id}`);load()}catch(e){setError(e.response?.data?.message||"Could not delete")}};
 const filtered=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 return <><div className="page-toolbar"><div><h2>{c.title}</h2><p className="muted">Maintain accurate {type} information.</p></div><button className="primary-button" onClick={()=>{setForm({});setEditing(null);setShow(true)}}>+ Add {type.slice(0,-1)}</button></div>{error&&<div className="alert">{error}</div>}<div className="filter-row"><input placeholder={`Search ${type}...`} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-card">{loading?<Loading/>:<table><thead><tr>{c.fields.map(f=><th key={f[0]}>{f[1]}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r._id}>{c.fields.map(f=><td key={f[0]}>{r[f[0]]||"—"}</td>)}<td><button className="text-button" onClick={()=>{setEditing(r._id);setForm(r);setShow(true)}}>Edit</button><button className="text-button danger-text" onClick={()=>remove(r._id)}>Delete</button></td></tr>)}</tbody></table>}{!loading&&!filtered.length&&<div className="empty-state">No records found.</div>}</div>{show&&<Modal title={editing?`Edit ${type.slice(0,-1)}`:`Add ${type.slice(0,-1)}`} onClose={()=>setShow(false)}><form className="form-grid" onSubmit={submit}>{c.fields.map(([k,l,t="text"])=> <label key={k}>{l}<input type={t} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==="name"}/></label>)}<label className="full-span">Notes<textarea value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions full-span"><button type="button" className="secondary-button" onClick={()=>setShow(false)}>Cancel</button><button className="primary-button">Save</button></div></form></Modal>}</>}
