import { useEffect, useState } from "react";
import API from "../services/api";
import Modal from "../components/Modal";
import Loading from "../components/Loading";

const blank = { name:"", sku:"", category:"", description:"", costPrice:"", sellingPrice:"", stock:"0", minStock:"0", unit:"pcs" };
const money = n => `₹${Number(n || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
export default function Products() {
    const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[search,setSearch]=useState(""),[category,setCategory]=useState(""),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
    const load=async()=>{setLoading(true);try{const [p,c]=await Promise.all([API.get("/products",{params:{search,category}}),API.get("/products/categories")]);setProducts(p.data);setCategories(c.data);}catch(e){setError(e.response?.data?.message||"Unable to load products")}finally{setLoading(false)}};
    useEffect(()=>{load()},[search,category]);
    const submit=async e=>{e.preventDefault();try{const body={...form,costPrice:Number(form.costPrice),sellingPrice:Number(form.sellingPrice),stock:Number(form.stock),minStock:Number(form.minStock)};if(editing) await API.put(`/products/${editing}`,body);else await API.post("/products",body);setShow(false);setEditing(null);setForm(blank);load()}catch(e){setError(e.response?.data?.message||"Could not save product")}};
    const edit=p=>{setEditing(p._id);setForm({...p,costPrice:String(p.costPrice),sellingPrice:String(p.sellingPrice),stock:String(p.stock),minStock:String(p.minStock)});setShow(true)};
    const remove=async id=>{if(!window.confirm("Delete this product?"))return;try{await API.delete(`/products/${id}`);load()}catch(e){setError(e.response?.data?.message||"Could not delete product")}};
    return <><div className="page-toolbar"><div><h2>Products</h2><p className="muted">Manage products, prices and stock.</p></div><button className="primary-button" onClick={()=>{setEditing(null);setForm(blank);setShow(true)}}>+ Add Product</button></div>{error&&<div className="alert">{error}</div>}<div className="filter-row"><input placeholder="Search name, SKU or category..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="table-card">{loading?<Loading/>:<table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Cost</th><th>Selling</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p._id}><td><strong>{p.name}</strong><small>{p.description}</small></td><td>{p.sku}</td><td>{p.category}</td><td>{money(p.costPrice)}</td><td>{money(p.sellingPrice)}</td><td>{p.stock} {p.unit}</td><td><span className={`status ${p.stock<=p.minStock?"danger":"success"}`}>{p.stock<=p.minStock?"Low stock":"In stock"}</span></td><td><button className="text-button" onClick={()=>edit(p)}>Edit</button><button className="text-button danger-text" onClick={()=>remove(p._id)}>Delete</button></td></tr>)}</tbody></table>}{!loading&&!products.length&&<div className="empty-state">No products found.</div>}</div>{show&&<Modal title={editing?"Edit Product":"Add Product"} onClose={()=>setShow(false)}><form className="form-grid" onSubmit={submit}>{[["name","Product name","text"],["sku","SKU","text"],["category","Category","text"],["unit","Unit","text"],["costPrice","Cost price","number"],["sellingPrice","Selling price","number"],["stock","Opening stock","number"],["minStock","Minimum stock","number"]].map(([k,l,t])=><label key={k}>{l}<input type={t} value={form[k]} min={t==="number"?0:undefined} step={t==="number"?"0.01":undefined} onChange={e=>setForm({...form,[k]:e.target.value})} required={!["unit"].includes(k)}/></label>)}<label className="full-span">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-actions full-span"><button type="button" className="secondary-button" onClick={()=>setShow(false)}>Cancel</button><button className="primary-button">Save Product</button></div></form></Modal>}</>;
}
